all task

diff --git a/basics_1/2-port_listening_on_localhost b/basics_1/2-port_listening_on_localhost
--- a/basics_1/2-port_listening_on_localhost
+++ b/basics_1/2-port_listening_on_localhost
@@ -1,3 +1,9 @@
 #!/usr/bin/env bash
+#script listen port 98
 
-nc -l -p 98
+if ! command -v nc &> /dev/null; then
+	echo "netcat is required."
+	exit 1
+fi
+
+nc -l -p 98 -s 127.0.0.1
